// token
export const SET_TOKEN = 'SET_TOKEN'
export const UNSET_TOKEN = 'UNSET_TOKEN'

// user
export const SET_USER = 'SET_USER'
export const UNSET_USER = 'UNSET_USER'

// redirection
export const SET_REDIRECT_TO = 'SET_REDIRECT_TO'
export const UNSET_REDIRECT_TO = 'UNSET_REDIRECT_TO'

// security
// client
export const SET_SECURITY_CLIENT_PRIVATE_KEY = 'SET_SECURITY_CLIENT_PRIVATE_KEY'
export const UNSET_SECURITY_CLIENT_PRIVATE_KEY = 'UNSET_SECURITY_CLIENT_PRIVATE_KEY'
export const SET_SECURITY_CLIENT_PUBLIC_KEY = 'SET_SECURITY_CLIENT_PUBLIC_KEY'
export const UNSET_SECURITY_CLIENT_PUBLIC_KEY = 'UNSET_SECURITY_CLIENT_PUBLIC_KEY'
export const SET_SECURITY_CLIENT_KEYS = 'SET_SECURITY_CLIENT_KEYS'
export const UNSET_SECURITY_CLIENT_KEYS = 'UNSET_SECURITY_CLIENT_KEYS'
// server
export const SET_SECURITY_SERVER_PUBLIC_KEY = 'SET_SECURITY_SERVER_PUBLIC_KEY'
export const UNSET_SECURITY_SERVER_PUBLIC_KEY = 'UNSET_SECURITY_SERVER_PUBLIC_KEY'
