// bookmarks
export const SET_BOOKMARKS = 'SET_BOOKMARKS'
export const UNSET_BOOKMARKS = 'UNSET_BOOKMARKS'
export const ADD_BOOKMARK = 'ADD_BOOKMARK'
export const EDIT_BOOKMARK = 'EDIT_BOOKMARK'
export const REMOVE_BOOKMARK = 'REMOVE_BOOKMARK'
